#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

admin=$(ynh_user_get_info --username=$admin --key=username)
admin_mail=$(ynh_user_get_info --username=$admin --key=mail)

# key for the .env __KEY__
key=$(ynh_string_random --length=45 | base64)
ynh_app_setting_set --app=$app --key=key --value=$key

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1

ynh_setup_source --dest_dir="$install_dir" --source_id="main"
ynh_setup_source --dest_dir="$install_dir/dotnet" --source_id="dotnet"

chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
# BUILD APP
#=================================================

pushd "$install_dir"
    $install_dir/dotnet/dotnet restore
popd

pushd "$install_dir/src/Presentation"
    $install_dir/dotnet/dotnet publish  -c Release -o build  --no-restore --verbosity m
popd

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression --message="Adding $app's configuration files..." --weight=1

ynh_add_config --template="../conf/.env" --destination="$install_dir/.env"

chmod 400 "$install_dir/.env"
chown $app:$app "$install_dir/.env"

#=================================================
# INSTALL APP
#=================================================

cp "$intall_dir/src/Presentation/build/*" "$install_dir/srv" --recursive

pushd "$install_dir/srv"
    $install_dir/dotnet/dotnet Presentation.dll
popd

chmod -R 660 "$install_dir"
chmod 770 "$install_dir"
chmod 770 "$install_dir/srv"
chown -R __APP__ "$install_dir"

#=================================================
# CONFIGURE THE SERVER PORTS
#=================================================

ynh_script_progression --message="Adding $app's configuration files..." --weight=1

ynh_secure_remove "$install_dir/srv/appsettings.json"
ynh_add_config --template="../conf/appsettings.json" --destination="$install_dir/srv/appsettings.json"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Adding system configurations related to $app..." --weight=1

ynh_add_nginx_config

ynh_add_systemd_config

yunohost service add "$app" --description="__APP__ service" --log="/var/log/$app/$app.log"

ynh_use_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting $app's systemd service..." --weight=1

ynh_systemd_action --service_name="$app" --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Installation of $app completed" --last
